# A sample Guardfile
# More info at https://github.com/guard/guard#readme

guard "lono" do
  watch(%r{^config/lono.rb$})
  watch(%r{^templates/.*$})
end

guard "cloudformation", :templates_path => "output" do
  watch(%r{^output/.+\.json$})
end